CREATE DATABASE vsn;

CREATE TABLE posts(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY;
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    img_url TEXT,
    created_ap TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

 DESCRIBE posts;