CREATE DATABASE vsn;

CREATE TABLE memo_list(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    deleted CHAR(1) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);
